{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "co-cell.serviceAccountName" . }}
  labels:
    {{- include "co-cell.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
